version: '3.8'

services:
  webapi:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw1rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
